Matplotlib	O
issue	O
on	O
OS	O
X	O
(	O
“ImportError	O
:	O
cannot	O
import	O
name	O
_thread”	O
)	O

At	O
some	O
point	O
in	O
the	O
last	O
few	O
days	O
,	O
Matplotlib	O
stopped	O
working	O
for	O
me	O
on	O
OS	O
X	O
.	O

Here's	O
the	O
error	O
I	O
get	O
when	O
trying	O
to	O
`	O
import	O
matplotlib	O
`	O
:	O

The	O
only	O
system	O
change	O
I	O
can	O
think	O
of	O
was	O
the	O
Apple-forced	O
NTP	O
update	O
and	O
maybe	O
some	O
permission	O
changes	O
I	O
did	O
in	O
/	O
usr	O
/	O
local	O
to	O
get	O
Brew	O
working	O
again	O
.	O

I	O
tried	O
reinstalling	O
both	O
Matplotlib	O
and	O
Python-dateutil	O
via	O
Pip	O
,	O
but	O
this	O
did	O
not	O
help	O
.	O

Also	O
tried	O
a	O
reboot	O
.	O

I'm	O
running	O
Python	O
2.7.6	O
,	O
which	O
is	O
located	O
in	O
/	O
usr	O
/	O
bin	O
/	O
python	O
.	O

I'm	O
running	O
Yosemite	O
(	O
OS	O
X	O
10.10.1	O
)	O
.	O

I	O
had	O
the	O
same	O
error	O
message	O
this	O
afternoon	O
as	O
well	O
,	O
although	O
I	O
did	O
recently	O
upgrade	O
to	O
Yosemite	O
.	O

I'm	O
not	O
totally	O
sure	O
I	O
understand	O
why	O
reverting	O
dateutil	O
to	O
a	O
previous	O
version	O
works	O
for	O
me	O
,	O
but	O
since	O
running	O
the	O
above	O
I'm	O
having	O
no	O
trouble	O
(	O
I	O
generally	O
use	O
pyplot	O
inline	O
in	O
an	O
ipython	O
notebook	O
)	O
.	O

Thanks	O
,	O
that	O
solved	O
the	O
issue	O
for	O
me	O
as	O
well	O
.	O

I	O
submitted	O
a	O
bug	O
to	O
the	O
developer	O
:	O
github.com/dateutil/dateutil/issues/12	O

I	O
think	O
updating	O
your	O
version	O
of	O
`	O
six	O
`	O
would	O
also	O
work	O
.	O

Thanks	O
for	O
your	O
suggestion	O
@USER	O
,	O
I	O
looked	O
into	O
it	O
and	O
I	O
am	O
already	O
running	O
the	O
latest	O
version	O
of	O
six	O
.	O

I	O
love	O
you	O
.	O

That	O
was	O
a	O
huge	O
waste	O
of	O
my	O
time	O
.	O

Almost	O
3	O
hours	O
have	O
breezed	O
by	O
and	O
this	O
one	O
answer	O
is	O
all	O
I	O
really	O
needed	O
.	O

Thank	O
you	O
.	O

Seems	O
to	O
be	O
a	O
new	O
issue	O
in	O
El	O
Capitan	O
--	O
an	O
old	O
version	O
of	O
"	O
six	O
"	O
is	O
included	O
in	O
''	O
/	O
System	O
/	O
Library	O
/	O
Frameworks	O
/	O
Python.framework	O
/	O
Versions	O
/	O
2.7	O
/	O
E	O
xtras	O
/	O
lib	O
/	O
python	O
/	O
six	O
.py	O
'	O
which	O
can't	O
be	O
upgraded	O
without	O
disabling	O
rootless	O
.	O

This	O
problem	O
is	O
fixed	O
in	O
the	O
latest	O
`	O
six	O
`	O
and	O
`	O
dateutil	O
`	O
versions	O
.	O

However	O
,	O
in	O
OS	O
X	O
,	O
even	O
if	O
you	O
update	O
your	O
`	O
six	O
`	O
to	O
the	O
latest	O
version	O
,	O
you	O
might	O
not	O
actually	O
update	O
it	O
correctly	O
.	O

This	O
is	O
what	O
happened	O
to	O
me	O
:	O

After	O
doing	O
a	O
`	O
pip2	O
install	O
six	O
-U	O
`	O
,	O
the	O
new	O
`	O
six	O
`	O
module	O
was	O
installed	O
in	O
`	O
/	O
Library	O
/	O
Python	O
/	O
2.7	O
/	O
site-packages	O
/	O
`	O
.	O

However	O
,	O
when	O
I	O
loaded	O
`	O
six	O
`	O
in	O
a	O
python	O
2.7	O
terminal	O
,	O
and	O
checked	O
its	O
path	O
,	O
this	O
is	O
what	O
I	O
got	O
:	O

So	O
,	O
python	O
was	O
using	O
an	O
old	O
version	O
of	O
`	O
six	O
`	O
,	O
which	O
I	O
removed	O
by	O
typing	O
:	O

This	O
fixed	O
this	O
issue	O
for	O
me	O
.	O

this	O
worked	O
for	O
me	O
on	O
Yosemite	O
.	O

this	O
worked	O
for	O
me	O
in	O
Yosemite	O
also	O
.	O

Thanks	O
for	O
sharing	O
..	O

The	O
only	O
answer	O
that	O
worked	O
for	O
me	O
.	O

Thank	O
you	O
.	O

this	O
worked	O
for	O
me	O

This	O
worked	O
for	O
me	O
on	O
10.10.4	O
(	O
I	O
also	O
have	O
a	O
newer	O
version	O
of	O
six	O
which	O
is	O
installed	O
by	O
pip	O
but	O
not	O
imported	O
by	O
default	O
)	O
.	O

Thanks	O
.	O

It	O
is	O
possible	O
that	O
you	O
have	O
a	O
perfectly	O
installed	O
version	O
of	O
any	O
packages	O
you	O
have	O
installed	O
,	O
but	O
the	O
version	O
used	O
by	O
default	O
is	O
not	O
the	O
one	O
you	O
want	O
.	O

You	O
can	O
see	O
the	O
list	O
of	O
paths	O
that	O
python	O
search	O
from	O
in	O
order	O
to	O
find	O
its	O
packages	O
as	O
follows	O
:	O

In	O
order	O
to	O
let	O
python	O
search	O
first	O
the	O
most	O
updated	O
version	O
of	O
certain	O
package	O
,	O
instead	O
of	O
removing	O
the	O
system	O
version	O
,	O
what	O
can	O
be	O
done	O
is	O
to	O
set	O
the	O
system	O
variable	O
`	O
PYTHONPATH	O
`	O
in	O
the	O
~	O
/	O
.bash_profile	O
(	O
or	O
~	O
/	O
.bashrc	O
if	O
linux	O
)	O
config	O
file	O
to	O
the	O
path	O
where	O
the	O
new	O
packages	O
are	O
installed	O
:	O

An	O
alternative	O
is	O
to	O
modify	O
the	O
python	O
path	O
inside	O
your	O
python	O
script	O
by	O
adding	O
the	O
path	O
at	O
the	O
beginning	O
of	O
the	O
path	O
list	O
:	O

This	O
needs	O
to	O
be	O
done	O
for	O
every	O
script	O
you	O
need	O
a	O
certain	O
package	O
version	O
.	O

You	O
might	O
want	O
for	O
some	O
reason	O
use	O
an	O
older	O
version	O
that	O
you	O
have	O
installed	O
.	O

BTW	O
all	O
my	O
installations	O
with	O
easy_install	O
,	O
or	O
pip	O
,	O
or	O
from	O
sources	O
go	O
to	O
/	O
Library	O
/	O
Python	O
/	O
2.7	O
/	O
site-packages	O

This	O
worked	O
en	O
EL	O
Capitan	O
,	O
and	O
now	O
also	O
in	O
macOS	O
Sierra	O
(	O
10.12.2	O
)	O

Installing	O
the	O
`	O
python-dateutil	O
==	O
2.2	O
`	O
did	O
not	O
work	O
for	O
me	O
.	O

But	O
a	O
quick-and-dirty	O
workaround	O
did	O
work	O
!	O

I	O
replace	O
`	O
six.py	O
`	O
in	O
python	O
2.7	O
with	O
the	O
`	O
six.py	O
`	O
from	O
python	O
3.4	O
(	O
virtualenv	O
)	O
.	O

Since	O
,	O
I	O
have	O
the	O
problem	O
in	O
2.7	O
but	O
not	O
3.4	O
.	O

UPDATE	O

I	O
had	O
the	O
same	O
problem	O
again	O
after	O
reinstalling	O
python	O
(	O
and	O
after	O
upgrading	O
to	O
El	O
Capitan	O
)	O
.	O

Un-obvious	O
thing	O
is	O
that	O
this	O
error	O
occurs	O
only	O
in	O
the	O
`	O
IPython	O
`	O
shell	O
and	O
notebook	O
(	O
when	O
I	O
do	O
`	O
import	O
matplotlib.pyplot	O
as	O
plt	O
`)	O
but	O
works	O
fine	O
from	O
a	O
Python	O
shell	O
.	O

So	O
a	O
better	O
solution	O
(	O
that	O
did	O
work	O
in	O
my	O
case	O
)	O
without	O
a	O
dirty	O
work-around	O
is	O
to	O
force	O
install	O
both	O
`	O
six	O
`	O
and	O
`	O
ipython	O
`	O
.	O

Here	O
is	O
what	O
I	O
did	O
to	O
have	O
this	O
fixed	O
:	O

I	O
have	O
the	O
same	O
issue	O
.	O

The	O
dateutil	O
fix	O
did	O
not	O
work	O
.	O

I	O
am	O
not	O
that	O
keen	O
to	O
hack	O
my	O
2.7	O
,	O
any	O
better	O
ideas	O
?	O

